local MobConfig = {}

-- Geometry and scale are owned exclusively by models under
-- ReplicatedStorage.Assets.Enemies.<Rank>. The runtime only applies gameplay data.
MobConfig.Mobs = {
	Slime = {
		hp = 22,
		speed = 8.5,
		attackRange = 3,
		attackCooldown = 1.9,
		damage = 5,
		xp = 5,
		coins = 1,
		movementProfile = "GroundSmall",
		resistanceProfile = "Slime",
	},
	Bat = {
		hp = 34,
		speed = 14.0,
		attackRange = 4,
		attackCooldown = 1.45,
		damage = 7,
		xp = 8,
		coins = 1,
		isRanged = false,
		canFly = true,
		movementMode = "Flying",
		movementProfile = "Flying",
		combatBehavior = "DiveAttack",
		preferredFlightAltitude = 10,
		idleAnimationId = "rbxassetid://77439435590958",
		runAnimationId = "rbxassetid://77439435590958",
		resistanceProfile = "FlyingBeast",
	},
	Goblin = {
		hp = 56,
		speed = 15.5,
		attackRange = 3,
		attackCooldown = 1.18,
		damage = 8,
		xp = 13,
		coins = 2,
		facingYawDegrees = -90,
		movementProfile = "GroundSmall",
		resistanceProfile = "Neutral",
	},
	Cauldron = {
		hp = 95,
		speed = 4.8,
		attackRange = 5,
		attackCooldown = 2.4,
		damage = 12,
		xp = 17,
		coins = 3,
		movementProfile = "GroundSmall",
		runAnimationId = "rbxassetid://92098878453446",
		resistanceProfile = "MetalConstruct",
	},
	Stump = {
		hp = 82,
		speed = 6.5,
		attackRange = 4.5,
		attackCooldown = 2.2,
		damage = 11,
		xp = 15,
		coins = 3,
		movementProfile = "GroundSmall",
		runAnimationId = "rbxassetid://98960191123613",
		resistanceProfile = "Wood",
	},
	Ent_Fat = {
		hp = 135,
		speed = 5.8,
		attackRange = 6,
		attackCooldown = 2.7,
		damage = 14,
		xp = 22,
		coins = 4,
		facingYawDegrees = -90,
		movementProfile = "GroundLarge",
		runAnimationId = "rbxassetid://71526519880141",
		resistanceProfile = "Wood",
	},
	Grzyb = {
		hp = 48,
		speed = 8.0,
		attackRange = 4,
		attackCooldown = 2.15,
		damage = 9,
		xp = 10,
		coins = 2,
		facingYawDegrees = -90,
		movementProfile = "GroundSmall",
		resistanceProfile = "Fungus",
	},
	Ent = {
		hp = 260,
		speed = 5.5,
		attackRange = 8,
		attackCooldown = 2.9,
		damage = 17,
		xp = 34,
		coins = 6,
		facingYawDegrees = -90,
		movementProfile = "GroundLarge",
		resistanceProfile = "Wood",
	},
	Golem = {
		hp = 210,
		speed = 6.5,
		attackRange = 6,
		attackCooldown = 2.6,
		damage = 18,
		xp = 30,
		coins = 5,
		facingYawDegrees = -90,
		movementProfile = "GroundLarge",
		resistanceProfile = "Stone",
	},
}

for _, config in pairs(MobConfig.Mobs) do
	config.range = config.attackRange
	config.cd = config.attackCooldown
	config.dmg = config.damage
end

return MobConfig
